[package]
name = "sbd"
version = "0.0.2"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]
description = "Read and write Iridium Short Burst Data (SBD) messages"
repository = "https://github.com/gadomski/sbd-rs"
documentation = "http://gadomski.github.io/sbd-rs"
keywords = ["iridium", "sbd"]
readme = "README.md"
license = "MIT"

[dependencies]
byteorder = "0.3"
enum_primitive = "0.1"
num = "0.1"
chrono = "0.2"
