[package]
name = "sbd"
version = "0.1.3"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]
description = "Read and write Iridium Short Burst Data (SBD) messages"
repository = "https://github.com/gadomski/sbd-rs"
documentation = "http://gadomski.github.io/sbd-rs"
keywords = ["iridium", "sbd"]
readme = "README.md"
license = "MIT/Apache-2.0"

[dependencies]
byteorder = "0.3"
chrono = "0.2"
docopt = "0.6"
log = "0.3"
rustc-serialize = "0.3"
tempdir = "0.3"
walkdir = "0.1"

[[bin]]
name = "sbd"
test = false
doc = false
